### ISSUE TITLE
sql

### ISSUE THREAD

**Issue by tanglongwei** [aadityabagga/bugtrackingportal#1]
hello,is there a sql  file to create the tables ??

**Comment by abchk1234** [comment]
Sure, will upload it shortly.

I had also been working on storing passwords as hashes instead of in clear text, will try to update that as well.

**Comment by abchk1234** [comment]
Hi,

Database scheme added:
https://github.com/aadityabagga/bugtrackingportal/blob/master/db/bugportal.sql

If you want database with actual data I can upload it too (it can be slightly confusing though).

I also added the part about storing passwords as hashes.

**Comment by abchk1234** [comment]
Closing..
